name: Deploy polygonId-demo
on:
  push:
    branches: [main]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
      DISABLE_ESLINT_PLUGIN: 'true'
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use specific node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build artifact
        run: npm run build

      - name: Deploy artifact to S3 and invalidate Cloudfront
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: build
          bucket: ${{ secrets.AWS_POLYGONIDDEMO_BUCKET }}
          dist-id: ${{ secrets.AWS_POLYGONIDDEMO_CLOUDFRONT_DIST_ID }}
          invalidation: / *
